#!/usr/bin/env bash
# Generate the engine migration from the vendored open-outcry SQL.
#
# All engine files are concatenated into ONE migration, in engine/manifest.txt
# order, so the schema is readable as a single unit and each object is defined
# once. Re-run this after updating the vendored SQL in engine/ to pull upstream
# changes — the generated file is never edited by hand.
#
# Goose directives are stripped and only the "Up" section is kept.
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
ENGINE="$ROOT/engine"
OUT="$ROOT/supabase/migrations"
DEST="$OUT/00010_engine.sql"

mkdir -p "$OUT"
# wipe previously generated engine migrations (both the old per-file scheme and
# the current single file); hand-written migrations are untouched.
find "$OUT" -name '0*_engine_*.sql' -delete 2>/dev/null || true
rm -f "$DEST"

strip_goose() {
  # print only the lines between "+goose Up" and "+goose Down",
  # dropping StatementBegin/StatementEnd markers.
  awk '
    /-- \+goose Up/      { up=1; next }
    /-- \+goose Down/    { up=0; next }
    /-- \+goose Statement(Begin|End)/ { next }
    up { print }
  ' "$1"
}

{
  printf -- '-- generated by scripts/gen-migrations.sh from engine/ — do not edit directly\n'
  printf -- '-- source: vendored open-outcry SQL, concatenated in engine/manifest.txt order\n'
} > "$DEST"

i=0
while IFS= read -r f; do
  [ -z "$f" ] && continue
  i=$((i+1))
  {
    printf -- '\n\n-- ── engine/%s ─────────────────────────────────────────────\n\n' "$f"
    strip_goose "$ENGINE/$f"
  } >> "$DEST"
done < "$ENGINE/manifest.txt"

echo "generated $DEST from $i engine files"
