-- generated by scripts/gen-migrations.sh from engine/ — do not edit directly
-- source: vendored open-outcry SQL, concatenated in engine/manifest.txt order


-- ── engine/pkg/models/transfer/transfer_type.sql ─────────────────────────────────────────────

CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
CREATE TYPE transfer_type AS ENUM (
    'DEPOSIT',
    'WITHDRAWAL',
    'TRANSFER',
    'INSTRUMENT_BUY',
    'INSTRUMENT_SELL',
    'CHARGE'
);



-- ── engine/pkg/models/trade_order/order_fill.sql ─────────────────────────────────────────────

CREATE TYPE order_fill AS ENUM (
    'FULL',
    'PARTIAL',
    'NONE'
);



-- ── engine/pkg/models/trade_order/order_side.sql ─────────────────────────────────────────────

CREATE TYPE order_side AS ENUM (
    'BUY',
    'SELL'
);



-- ── engine/pkg/models/trade_order/order_type.sql ─────────────────────────────────────────────

CREATE TYPE order_type AS ENUM (
    'LIMIT',
    'MARKET',
    'STOPLOSS',
    'STOPLIMIT'
);



-- ── engine/pkg/models/trade_order/trade_order_status.sql ─────────────────────────────────────────────

-- Model of states that a trade order can undergo during its
-- lifecycle. Transitional states hold funds in `currency_account.amount_reserved`
-- Final states should release all reserved funds.
CREATE TYPE trade_order_status AS ENUM(
    -- TRANSITIONAL STATES
    -- order remains in the order book and has no fills
    'OPEN',
    -- order remains in the order book but with partial fill
    'PARTIALLY_FILLED',
    -- FINAL STATES
    -- order has been cancelled by the user without any fills
    'CANCELLED',
    -- order has been partially filled but then cancelled by user
    'PARTIALLY_CANCELLED',
    -- order has been partially filled but then rejected.
    -- Possible rejection reasons:
    --  * IOC
    --  * GTD
    --  * GTT
    'PARTIALLY_REJECTED',
    -- order has been filled and removed from the order book
    'FILLED',
    -- order rejected from the order book.
    -- Possible rejection reasons:
    --  * insufficiency of funds
    --  * FOK or IOC order that cannot be filled
    'REJECTED'
);



-- ── engine/pkg/models/trade_order/order_time_in_force.sql ─────────────────────────────────────────────

-- time constraints imposed on the order
CREATE TYPE order_time_in_force AS ENUM (
    -- good-til-cancelled (GTC) orders require a specific cancelling order, which can persist infinitely
    -- this is the default state for all orders
    'GTC',

    -- an immediate or cancel (IOC) orders are immediately executed or cancelled by the exchange.
    -- Unlike FOK orders, IOC orders allow for partial fills.
    'IOC',

    -- Fill or kill (FOK) orders are usually limit orders that must be executed or cancelled immediately.
    -- Unlike IOC orders, FOK orders require the full quantity to be executed.
    'FOK',

    -- Good till date orders are valid until a certain date. The order gets
    -- canceled at the END of the day, if it is not executed.
    'GTD',

    -- Good till time orders are valid until a certain time with minute precision
    'GTT'
);



-- ── engine/pkg/models/transfer/ledger_entry_type.sql ─────────────────────────────────────────────

DO $$ BEGIN
    CREATE TYPE ledger_entry_type AS ENUM ('DEBIT', 'CREDIT');
EXCEPTION
    WHEN duplicate_object THEN null;
END $$;



-- ── engine/pkg/models/app_entity/app_entity.sql ─────────────────────────────────────────────

CREATE TABLE app_entity
(
    id                  BIGSERIAL PRIMARY KEY,
    pub_id              TEXT default uuid_generate_v4() UNIQUE NOT NULL,
    type                TEXT NOT NULL,   -- CLIENT, MASTER
    external_id         TEXT NOT NULL,
    updated_at          TIMESTAMPTZ default current_timestamp NOT NULL,
    created_at          TIMESTAMPTZ default current_timestamp NOT NULL
);

CREATE INDEX idx_app_entity_type ON app_entity(type);
CREATE INDEX idx_app_entity_external_id ON app_entity(external_id);



-- ── engine/pkg/models/currency/currency.sql ─────────────────────────────────────────────

CREATE TABLE currency (
   name                               TEXT PRIMARY KEY,
   precision                          INT default 2 NOT NULL
);



-- ── engine/pkg/models/currency_account/currency_account.sql ─────────────────────────────────────────────

CREATE TABLE currency_account (
    id                      BIGSERIAL PRIMARY KEY,
    pub_id                  TEXT default uuid_generate_v4() UNIQUE NOT NULL,
    app_entity_id           BIGINT REFERENCES app_entity(id) NOT NULL,
    amount                  NUMERIC default 0.00 NOT NULL
                            CHECK (amount >= 0),
    amount_reserved         NUMERIC default 0.00 NOT NULL
                            CHECK (amount_reserved >= 0 and amount_reserved <= amount),
    currency_name           TEXT REFERENCES currency(name) NOT NULL,
    updated_at              TIMESTAMPTZ default current_timestamp NOT NULL,
    created_at              TIMESTAMPTZ default current_timestamp NOT NULL,

    -- enforce one currency account per application entity
    UNIQUE (app_entity_id, currency_name)
);

CREATE INDEX idx_currency_account_currency_name ON currency_account(currency_name);



-- ── engine/pkg/models/transfer/transfer.sql ─────────────────────────────────────────────


-- Journal entry: one record per transfer linking two ledger entries
CREATE TABLE transfer (
       id                                   BIGSERIAL PRIMARY KEY,
       pub_id                               TEXT default uuid_generate_v4() UNIQUE NOT NULL,
       type                                 transfer_type NOT NULL,
       amount                               NUMERIC default 0.00 NOT NULL CHECK (amount > 0),
       currency_name                        TEXT REFERENCES currency(name) NOT NULL,
       details                              TEXT NOT NULL,
       external_reference_number            TEXT NULL,
       status                               TEXT NOT NULL,
       updated_at                           TIMESTAMPTZ default current_timestamp NOT NULL,
       created_at                           TIMESTAMPTZ default current_timestamp NOT NULL
);

CREATE INDEX idx_transfer_currency_name ON transfer(currency_name);

-- Double-entry ledger: every transfer produces exactly two entries (DEBIT + CREDIT)
CREATE TABLE transfer_ledger_entry (
       id                                   BIGSERIAL PRIMARY KEY,
       pub_id                               TEXT default uuid_generate_v4() UNIQUE NOT NULL,
       transfer_id                          BIGINT REFERENCES transfer(id) ON DELETE CASCADE NOT NULL,
       currency_account_id                  BIGINT REFERENCES currency_account(id) NOT NULL,
       entry_type                           ledger_entry_type NOT NULL,
       amount                               NUMERIC default 0.00 NOT NULL CHECK (amount > 0),
       -- Resulting balance after this entry
       resulting_balance                    NUMERIC default 0.00 NOT NULL
                                            CHECK (resulting_balance >= 0),
       created_at                           TIMESTAMPTZ default current_timestamp NOT NULL
);

CREATE INDEX idx_tle_transfer_id ON transfer_ledger_entry(transfer_id);
CREATE INDEX idx_tle_currency_account_id ON transfer_ledger_entry(currency_account_id);



-- ── engine/pkg/models/fee/fee.sql ─────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS fee (
     type                               TEXT NOT NULL,
     currency_name                      TEXT REFERENCES currency(name) NOT NULL,
     min                                NUMERIC NULL,
     max                                NUMERIC NULL,
     percentage                         NUMERIC NULL,
     updated_at                         TIMESTAMPTZ default current_timestamp NOT NULL,
     created_at                         TIMESTAMPTZ default current_timestamp NOT NULL,
     PRIMARY KEY(type, currency_name)
);



-- ── engine/pkg/models/instrument/instrument.sql ─────────────────────────────────────────────

CREATE TABLE instrument(
    id              BIGSERIAL PRIMARY KEY,
    pub_id          TEXT default uuid_generate_v4() UNIQUE NOT NULL,
    name            TEXT UNIQUE NOT NULL,
    quote_currency  TEXT NOT NULL,
    -- fx instruments involve an exchange of currencies 
    fx_instrument   BOOLEAN NOT NULL default FALSE,
    base_currency   TEXT NULL,
    enabled         BOOLEAN NOT NULL default TRUE
);



-- ── engine/pkg/models/order_book/price_level.sql ─────────────────────────────────────────────

-- price levels for instrument allow for fast access to volumes of orders
CREATE TABLE price_level(
    id              BIGSERIAL PRIMARY KEY,
    price           NUMERIC NOT NULL,
    side            order_side NOT NULL,
    instrument_id   BIGINT REFERENCES instrument(id),
    volume          NUMERIC NOT NULL default 0
);

CREATE INDEX idx_price_level_instrument_id ON price_level(instrument_id);
CREATE INDEX idx_price_level_instrument_price_side ON price_level(instrument_id, price, side);



-- ── engine/pkg/models/instrument_account/instrument_account.sql ─────────────────────────────────────────────

-- Instrument account belonging to application entity
CREATE TABLE instrument_account (
    id                      BIGSERIAL PRIMARY KEY,
    pub_id                  TEXT default uuid_generate_v4() UNIQUE NOT NULL,
    app_entity_id           BIGINT REFERENCES app_entity(id) NOT NULL,
    updated_at              TIMESTAMPTZ default current_timestamp NOT NULL,
    created_at              TIMESTAMPTZ default current_timestamp NOT NULL
);

CREATE INDEX idx_instrument_account_app_entity_id ON instrument_account(app_entity_id);



-- ── engine/pkg/models/instrument_account/instrument_account_holding.sql ─────────────────────────────────────────────

-- for non monetary instruments, instruments must be credited directly to instrument account
CREATE TABLE instrument_account_holding (
    id                      BIGSERIAL PRIMARY KEY,
    pub_id                  TEXT default uuid_generate_v4() UNIQUE NOT NULL,
    instrument_account      BIGINT REFERENCES instrument_account(id) NOT NULL,
    amount                  BIGINT default 0 NOT NULL
        CHECK (amount >= 0),
    amount_reserved         BIGINT default 0 NOT NULL
        CHECK (amount >= 0),

    instrument_id           BIGINT REFERENCES instrument(id) NOT NULL,
    updated_at              TIMESTAMPTZ default current_timestamp NOT NULL,
    created_at              TIMESTAMPTZ default current_timestamp NOT NULL,

    -- enforce one instrument_account_holding per instrument_account
    UNIQUE (instrument_account, instrument_id)
);

CREATE INDEX idx_tai_instrument_id ON instrument_account_holding(instrument_id);



-- ── engine/pkg/models/instrument_account/instrument_account_transfer.sql ─────────────────────────────────────────────


-- Journal entry: one record per transfer linking two ledger entries
CREATE TABLE instrument_account_transfer (
       id                                 BIGSERIAL PRIMARY KEY,
       pub_id                             TEXT default uuid_generate_v4() UNIQUE NOT NULL,
       instrument_id                      BIGINT REFERENCES instrument(id) NOT NULL,
       amount                             INTEGER default 0 NOT NULL CHECK (amount > 0),
       details                            TEXT NULL,
       external_reference_number          TEXT NULL,
       updated_at                         TIMESTAMPTZ default current_timestamp NOT NULL,
       created_at                         TIMESTAMPTZ default current_timestamp NOT NULL
);


-- Double-entry ledger: every transfer produces exactly two entries (DEBIT + CREDIT)
CREATE TABLE instrument_account_ledger_entry (
       id                                 BIGSERIAL PRIMARY KEY,
       pub_id                             TEXT default uuid_generate_v4() UNIQUE NOT NULL,
       transfer_id                        BIGINT REFERENCES instrument_account_transfer(id) NOT NULL,
       instrument_account_holding_id      BIGINT REFERENCES instrument_account_holding(id) NOT NULL,
       entry_type                         ledger_entry_type NOT NULL,
       amount                             INTEGER default 0 NOT NULL CHECK (amount > 0),
       -- Resulting balance after this entry
       resulting_balance                  INTEGER default 0 NOT NULL CHECK (resulting_balance >= 0),
       created_at                         TIMESTAMPTZ default current_timestamp NOT NULL
);

CREATE INDEX idx_tat_instrument_id ON instrument_account_transfer(instrument_id);
CREATE INDEX idx_tale_transfer_id ON instrument_account_ledger_entry(transfer_id);
CREATE INDEX idx_tale_tai_id ON instrument_account_ledger_entry(instrument_account_holding_id);



-- ── engine/pkg/models/trade_order/trade_order.sql ─────────────────────────────────────────────

CREATE TABLE trade_order(
    id                  BIGSERIAL PRIMARY KEY,
    pub_id              TEXT default uuid_generate_v4() UNIQUE NOT NULL,
    instrument_account_id  BIGINT REFERENCES instrument_account(id) NOT NULL,
    instrument_id       BIGINT REFERENCES instrument(id) NOT NULL,
    order_type          order_type NOT NULL,
    side                order_side NOT NULL,
    time_in_force       order_time_in_force NOT NULL,
    price               DECIMAL NOT NULL,
    amount              DECIMAL NOT NULL,
    open_amount         DECIMAL NOT NULL,
    status              trade_order_status NOT NULL default 'OPEN',
    updated_at          TIMESTAMPTZ default current_timestamp NOT NULL,
    created_at          TIMESTAMPTZ default current_timestamp NOT NULL
);

CREATE INDEX idx_trade_order_instrument_side_status ON trade_order(instrument_id, side, status);
CREATE INDEX idx_trade_order_instrument_account_id ON trade_order(instrument_account_id);



-- ── engine/pkg/models/trade/trade.sql ─────────────────────────────────────────────

CREATE TABLE trade (
    id              BIGSERIAL PRIMARY KEY,
    pub_id          TEXT default uuid_generate_v4() UNIQUE NOT NULL,
    instrument_id   BIGINT REFERENCES instrument(id) NOT NULL,
    price           DECIMAL NOT NULL,
    amount          DECIMAL NOT NULL,
    seller_order_id BIGINT REFERENCES trade_order(id) NOT NULL,
    buyer_order_id  BIGINT REFERENCES trade_order(id) NOT NULL,
    taker_order_id  BIGINT REFERENCES trade_order(id) NOT NULL, -- the order acting opposite of maker
    updated_at      TIMESTAMPTZ default current_timestamp NOT NULL,
    created_at      TIMESTAMPTZ default current_timestamp NOT NULL
);

CREATE INDEX idx_trade_instrument_created ON trade(instrument_id, created_at DESC);
CREATE INDEX idx_trade_seller_order ON trade(seller_order_id);
CREATE INDEX idx_trade_buyer_order ON trade(buyer_order_id);
CREATE INDEX idx_trade_taker_order ON trade(taker_order_id);



-- ── engine/pkg/models/order_book/book_order.sql ─────────────────────────────────────────────

CREATE TABLE book_order(
    id                  BIGSERIAL PRIMARY KEY,
    pub_id              TEXT default uuid_generate_v4() UNIQUE NOT NULL,
    trade_order_id      BIGINT REFERENCES trade_order(id) ON DELETE CASCADE UNIQUE NOT NULL
);



-- ── engine/pkg/models/trade_order/stop_order.sql ─────────────────────────────────────────────

CREATE TABLE stop_order(
    id                  BIGSERIAL PRIMARY KEY,
    pub_id              TEXT default uuid_generate_v4() UNIQUE NOT NULL,
    price               DECIMAL NOT NULL,           -- trigger price
    trade_order_id      BIGINT REFERENCES trade_order(id) UNIQUE NOT NULL
);



-- ── engine/pkg/services/order_book/banker_round.sql ─────────────────────────────────────────────


-- round-half-even aka Banker's rounding
CREATE OR REPLACE FUNCTION
    banker_round(val NUMERIC, prec INTEGER)
    returns NUMERIC

LANGUAGE 'plpgsql' IMMUTABLE
AS $$
DECLARE
    retval NUMERIC;
    difference NUMERIC;
    even BOOLEAN;
BEGIN
    IF val IS NULL OR
    prec IS NULL THEN
        RAISE EXCEPTION 'param_cannot_be_null val: %, prec %', val, prec;
    END IF;

    retval := round(val,prec);
    difference := retval-val;
    IF abs(difference)*(10::NUMERIC^prec) = 0.5::NUMERIC THEN
        even := (retval * (10::NUMERIC^prec)) % 2::NUMERIC = 0::NUMERIC;
        IF NOT even THEN
            retval := round(val-difference,prec);
        END IF;
    END IF;
    RETURN retval;
END;
$$;



-- ── engine/pkg/services/transfer/create_currency_account.sql ─────────────────────────────────────────────

-- Create currency account for application entity; return an existing account if already exists
CREATE OR REPLACE FUNCTION create_currency_account(app_entity_id_param text, currency_param text)
    RETURNS text -- currency_account.pub_id
    LANGUAGE 'plpgsql'
    AS $$
DECLARE
    app_entity_instance app_entity%ROWTYPE;
    currency_account_instance currency_account%ROWTYPE;
    currency_instance currency%ROWTYPE;
BEGIN
    SELECT * FROM app_entity
    WHERE pub_id = app_entity_id_param INTO app_entity_instance;
    IF NOT FOUND THEN
        RAISE EXCEPTION 'app_entity_instance_not_found';
    END IF;
    SELECT * FROM currency
    WHERE name = currency_param INTO currency_instance;
    IF NOT FOUND THEN
        RAISE EXCEPTION 'currency_instance_not_found';
    END IF;
    -- prevent duplicates
    SELECT * FROM currency_account
    WHERE currency_name = currency_instance.name
        AND app_entity_id = app_entity_instance.id INTO currency_account_instance;
    IF NOT FOUND THEN
        INSERT INTO currency_account(app_entity_id, currency_name)
            VALUES (app_entity_instance.id, currency_instance.name)
        RETURNING * INTO currency_account_instance;
    END IF;
    RETURN currency_account_instance.pub_id;
END;
$$;


-- ── engine/pkg/services/transfer/create_transfer.sql ─────────────────────────────────────────────

CREATE OR REPLACE FUNCTION
  create_transfer(
      type_param transfer_type,
      from_customer_id_param text,
      amount_param numeric,
      currency_param text,
      to_customer_id_param text,
      reference_param text,
      details_param text
  )
  RETURNS TEXT -- transfer_instance.pub_id
LANGUAGE 'plpgsql'
AS $$
DECLARE
    from_currency_account_instance currency_account%ROWTYPE;
    to_currency_account_instance currency_account%ROWTYPE;
    transfer_instance transfer%ROWTYPE;
    currency_instance currency%ROWTYPE;
BEGIN
  IF from_customer_id_param = to_customer_id_param THEN
    RAISE EXCEPTION 'Self-transfer not allowed --> (%, %)', from_customer_id_param, to_customer_id_param;
  END IF;
  SELECT * FROM currency
  WHERE name = currency_param
  INTO currency_instance;
  IF NOT FOUND THEN
      RAISE EXCEPTION 'currency_instance_not_found';
  END IF;
  SELECT * FROM currency_account
  WHERE app_entity_id =
        (SELECT id FROM app_entity
         WHERE pub_id = from_customer_id_param)
  AND currency_name = currency_instance.name
  INTO from_currency_account_instance;
  IF NOT FOUND THEN
      RAISE EXCEPTION 'from_currency_account_instance_not_found';
  END IF;
  -- check sufficiency of funds in case of non-master accounts
  IF from_customer_id_param != 'MASTER' THEN
    IF from_currency_account_instance.amount < amount_param THEN
      RAISE EXCEPTION 'insufficient_funds available: %, required % ', from_currency_account_instance.amount, amount_param;
    END IF;
  END IF;
  SELECT * FROM currency_account
  WHERE app_entity_id =
        (SELECT id FROM app_entity
         WHERE pub_id = to_customer_id_param)
  AND currency_name = currency_instance.name
  INTO to_currency_account_instance;
  IF NOT FOUND THEN
      RAISE EXCEPTION 'to_currency_account_instance_not_found';
  END IF;
  -- 1. Create the journal entry (transfer header)
  INSERT INTO transfer (
      type,
      amount,
      currency_name,
      details,
      external_reference_number,
      status
  ) VALUES (
      type_param,
      amount_param,
      currency_instance.name,
      details_param,
      reference_param,
      'COMPLETE'
  ) RETURNING * INTO transfer_instance;
  -- 2. Create DEBIT ledger entry (sender side: decrease)
  INSERT INTO transfer_ledger_entry (
      transfer_id,
      currency_account_id,
      entry_type,
      amount,
      resulting_balance
  ) VALUES (
      transfer_instance.id,
      from_currency_account_instance.id,
      'DEBIT',
      amount_param,
      (CASE WHEN from_customer_id_param = 'MASTER' THEN 0 ELSE from_currency_account_instance.amount - amount_param END)
  );
  -- 3. Create CREDIT ledger entry (receiver side: increase)
  INSERT INTO transfer_ledger_entry (
      transfer_id,
      currency_account_id,
      entry_type,
      amount,
      resulting_balance
  ) VALUES (
      transfer_instance.id,
      to_currency_account_instance.id,
      'CREDIT',
      amount_param,
      (CASE WHEN to_customer_id_param = 'MASTER' THEN 0 ELSE to_currency_account_instance.amount + amount_param END)
  );
  -- 4. Update sender balance (debit reduces the balance)
  IF from_customer_id_param != 'MASTER' THEN
    UPDATE currency_account
    SET amount = from_currency_account_instance.amount - amount_param,
        amount_reserved = (
          CASE WHEN type_param = 'INSTRUMENT_SELL'::transfer_type
               OR type_param = 'INSTRUMENT_BUY'::transfer_type
          THEN from_currency_account_instance.amount_reserved - amount_param
          ELSE from_currency_account_instance.amount_reserved END
        ),
        updated_at = current_timestamp
    WHERE id = from_currency_account_instance.id;
  END IF;
  -- 5. Update receiver balance (credit increases the balance)
  IF to_customer_id_param != 'MASTER' THEN
    UPDATE currency_account
    SET amount = to_currency_account_instance.amount + amount_param,
        updated_at = current_timestamp
    WHERE id = to_currency_account_instance.id;
  END IF;
  RETURN transfer_instance.pub_id;
END;
$$;


-- ── engine/pkg/services/transfer/process_transfer.sql ─────────────────────────────────────────────

CREATE OR REPLACE FUNCTION
    process_transfer(
        type_param transfer_type,
        from_customer_id_param TEXT,
        amount_param NUMERIC,
        currency_param TEXT,
        to_customer_id_param TEXT,
        reference_param TEXT,
        details_param TEXT,
        fee_type_param TEXT
    )
    RETURNS TEXT -- transfer_instance.pub_id
    LANGUAGE 'plpgsql'
AS $$
DECLARE
    transfer_instance_pub_id_var TEXT;
    currency_instance currency%ROWTYPE;
    fee_instance fee%ROWTYPE;
    fee_amount_var NUMERIC = 0.00;
BEGIN
    transfer_instance_pub_id_var = create_transfer(type_param, from_customer_id_param, amount_param, currency_param, to_customer_id_param, reference_param, details_param);
    -- create fee transfer
    IF fee_type_param IS NOT NULL THEN
        SELECT * FROM fee
        WHERE type = fee_type_param AND currency_name = currency_param
        INTO fee_instance;
        IF FOUND THEN
            -- priority is given to percentage
            IF fee_instance.percentage IS NOT NULL THEN
                fee_amount_var = banker_round(amount_param * fee_instance.percentage / 100,  currency_instance.precision);
            END IF;
            -- check min
            IF fee_instance.min IS NOT NULL THEN
                IF fee_amount_var < fee_instance.min THEN
                    fee_amount_var = fee_instance.min;
                END IF;
            END IF;
            -- check max
            IF fee_instance.max IS NOT NULL THEN
                IF fee_amount_var > fee_instance.max THEN
                    fee_amount_var = fee_instance.max;
                END IF;
            END IF;
            PERFORM create_transfer(
                'CHARGE'::transfer_type,
                to_customer_id_param,
                fee_amount_var,
                currency_param,
                'MASTER',
                transfer_instance_pub_id_var,
                transfer_instance_pub_id_var
            );
        END IF;
    END IF;
    RETURN transfer_instance_pub_id_var;
END;
$$;


-- ── engine/pkg/services/registration/create_client.sql ─────────────────────────────────────────────


CREATE OR REPLACE FUNCTION
  create_client(
    external_id_param text
  )

  -- app_entity.pub_id
  RETURNS TEXT

LANGUAGE 'plpgsql'
AS $$
DECLARE
  app_entity_instance app_entity%ROWTYPE;
BEGIN
  -- create app_entity
  INSERT INTO app_entity (external_id, type)
  VALUES (external_id_param, 'CUSTOMER')
  RETURNING * INTO app_entity_instance;

  -- attach currency account for some default currency - assume 'EUR' for now
  PERFORM create_currency_account(app_entity_instance.pub_id, 'EUR');

  -- attach instrument account
  INSERT INTO instrument_account(app_entity_id)
  VALUES (app_entity_instance.id);

  -- TO{ onboarding state
  RETURN app_entity_instance.pub_id;
END;
$$;




-- ── engine/pkg/services/order_book/get_crossing_limit_orders.sql ─────────────────────────────────────────────


CREATE OR REPLACE FUNCTION
    get_crossing_limit_orders(
        instrument_id_param BIGINT,
        side_param order_side,
        price_param NUMERIC,
        trade_account_id_param BIGINT
    )
    RETURNS setof book_order
    LANGUAGE 'plpgsql'
AS $$
BEGIN
    IF instrument_id_param IS NULL 
    OR side_param IS NULL
    OR price_param IS NULL
    OR trade_account_id_param IS NULL 
    THEN
        RAISE EXCEPTION 'param_cannot_be_null %, %, %, %',
            instrument_id_param,
            side_param,
            price_param,
            trade_account_id_param;
    END IF;
    
    IF price_param = 0 THEN
        -- handle market orders
        IF side_param = 'SELL' THEN
            RETURN QUERY SELECT b.id, b.pub_id, b.trade_order_id FROM book_order b
            INNER JOIN trade_order t
                ON b.trade_order_id = t.id
            WHERE t.instrument_id = instrument_id_param
                AND t.side = side_param
                AND t.instrument_account_id != trade_account_id_param
                AND t.order_type = 'LIMIT'::order_type
            -- order first by price then by date created
            ORDER BY t.price, t.created_at;
        ELSE
            RETURN QUERY SELECT b.id, b.pub_id, b.trade_order_id FROM book_order b
            INNER JOIN trade_order t
                ON b.trade_order_id = t.id
            WHERE t.instrument_id = instrument_id_param
                AND t.side = side_param
                AND t.instrument_account_id != trade_account_id_param
                AND t.order_type = 'LIMIT'::order_type
            -- order first by price then by date created
            ORDER BY t.price DESC, t.created_at;
        END IF;
    ELSE
        -- handle limit order
        IF side_param = 'SELL' THEN
            RETURN QUERY SELECT b.id, b.pub_id, b.trade_order_id FROM book_order b
            INNER JOIN trade_order t
                ON b.trade_order_id = t.id
            WHERE t.instrument_id = instrument_id_param
                AND t.side = side_param
                AND t.instrument_account_id != trade_account_id_param
                AND t.order_type = 'LIMIT'::order_type
                AND t.price <= price_param
            -- order first by price then by date created
            ORDER BY t.price, t.created_at;
        ELSE
            RETURN QUERY SELECT b.id, b.pub_id, b.trade_order_id FROM book_order b
            INNER JOIN trade_order t
                ON b.trade_order_id = t.id
            WHERE t.instrument_id = instrument_id_param
                AND t.side = side_param
                AND t.instrument_account_id != trade_account_id_param
                AND t.order_type = 'LIMIT'::order_type
                AND t.price >= price_param
            -- order first by price then by date created
            ORDER BY t.price DESC, t.created_at;
        END IF;
    END IF;
END;
$$;



-- ── engine/pkg/services/order_book/get_available_limit_volume.sql ─────────────────────────────────────────────


-- Returns available limit order volume in base currency
CREATE OR REPLACE FUNCTION get_available_limit_volume(
    instrument_id_param BIGINT,
    side_param order_side,
    price_param DECIMAL
)
    RETURNS NUMERIC
    LANGUAGE 'plpgsql'

AS $$
DECLARE
    acc NUMERIC := 0;
BEGIN
    IF price_param = 0 THEN
        IF side_param = 'SELL' THEN
            SELECT SUM(volume)
            FROM price_level
            WHERE side = side_param
            AND instrument_id = instrument_id_param
            AND price != 0.00
            INTO acc;
        ELSE
            SELECT SUM(volume)
            FROM price_level
            WHERE side = side_param
            AND instrument_id = instrument_id_param
            AND price != 0.00
            INTO acc;        
        END IF;
    ELSE
        IF side_param = 'SELL' THEN
            SELECT SUM(volume)
            FROM price_level
            WHERE side = side_param
            AND instrument_id = instrument_id_param
            AND price <=  price_param 
            AND price != 0.00
            INTO acc;
        ELSE
            SELECT SUM(volume)
            FROM price_level
            WHERE side = side_param
            AND instrument_id = instrument_id_param
            AND price >=  price_param 
            INTO acc;        
        END IF;
    END IF;

    IF acc IS NULL THEN
        RETURN 0.00;
    END IF;

    RETURN acc;
END;
$$;



-- ── engine/pkg/services/order_book/get_best_limit_price.sql ─────────────────────────────────────────────


CREATE OR REPLACE FUNCTION get_best_limit_price(
    instrument_id_param BIGINT,
    side_param order_side
)
RETURNS NUMERIC
LANGUAGE 'plpgsql'

AS $$
DECLARE
    acc NUMERIC := 0;
BEGIN
    IF side_param = 'SELL'::order_side THEN
        SELECT price
        FROM price_level
        WHERE side = side_param
        AND instrument_id = instrument_id_param
        AND price > 0
        ORDER BY price
        LIMIT 1
        INTO acc;
    ELSEIF side_param = 'BUY'::order_side THEN
        SELECT price
        FROM price_level
        WHERE side = side_param
        AND instrument_id = instrument_id_param
        AND price > 0
        ORDER BY price DESC
        LIMIT 1
        INTO acc;        
    ELSE
        RAISE EXCEPTION 'invalid side %', side_param;
    END IF;

    IF acc IS NULL THEN
        RETURN -1;
    END IF;

    RETURN acc;
END;
$$;



-- ── engine/pkg/services/matching/get_fill_type.sql ─────────────────────────────────────────────



-- determine fill amount for order
CREATE OR REPLACE 

    FUNCTION get_fill_type(
        open_amount NUMERIC, -- the amount left in the incoming trade
        available_amount NUMERIC -- the amount left in the book order
    )
    RETURNS order_fill

LANGUAGE 'plpgsql' IMMUTABLE
AS $$
BEGIN
    IF available_amount >= open_amount THEN
        RETURN 'FULL'::order_fill;
    elseif available_amount > 0.00 then
        RETURN 'PARTIAL'::order_fill;
    ELSE
        RETURN 'NONE'::order_fill;
    END IF;
END;
$$;


-- *goose Down
DROP FUNCTION get_fill_type(NUMERIC, NUMERIC);


-- ── engine/pkg/services/matching/create_trade.sql ─────────────────────────────────────────────


-- create a trade and execute settlement between clients
-- open amounts for trade orders are updated
-- price levels are updated
CREATE OR REPLACE FUNCTION
    create_trade(
        instrument_param instrument,
        price_param DECIMAL,
        amount_param DECIMAL,
        seller_trade_order_param trade_order,
        buyer_trade_order_param trade_order,
        taker_trade_order_param trade_order
    )
    RETURNS void
    LANGUAGE 'plpgsql'
AS $$
DECLARE
    trade_instance trade%ROWTYPE;
    master_app_entity_instance app_entity%ROWTYPE;
    seller_app_entity_instance app_entity%ROWTYPE;
    buyer_app_entity_instance app_entity%ROWTYPE;
BEGIN

    INSERT INTO trade (
        instrument_id,
        price,
        amount,
        seller_order_id,
        buyer_order_id,
        taker_order_id
    )
    VALUES (
        instrument_param.id,
        price_param,
        amount_param,
        seller_trade_order_param.id,
        buyer_trade_order_param.id,
        taker_trade_order_param.id
    )
    RETURNING * INTO trade_instance;

    IF NOT FOUND THEN
        RAISE EXCEPTION 'trade_instance_not_created';
    END IF;

    -- set up master
    SELECT * FROM app_entity
    WHERE type = 'MASTER'
    INTO master_app_entity_instance;

    IF NOT FOUND THEN
        RAISE EXCEPTION 'master_app_entity_instance_not_found';
    END IF;

    -- set up seller
    SELECT * FROM app_entity
    INNER JOIN instrument_account
        ON instrument_account.app_entity_id = app_entity.id
    INNER JOIN trade_order
        ON trade_order.instrument_account_id = instrument_account.id
    WHERE trade_order.id = seller_trade_order_param.id
    INTO seller_app_entity_instance;

    IF NOT FOUND THEN
        RAISE EXCEPTION 'seller_app_entity_instance_not_found';
    END IF;

    -- set up buyer
    SELECT * FROM app_entity
    INNER JOIN instrument_account
        ON instrument_account.app_entity_id = app_entity.id
    INNER JOIN trade_order
        ON trade_order.instrument_account_id = instrument_account.id
    WHERE trade_order.id = buyer_trade_order_param.id
    INTO buyer_app_entity_instance;

    IF NOT FOUND THEN
        RAISE EXCEPTION 'buyer_app_entity_instance_not_found';
    END IF;

    -- EXECUTE TRANSFERS FOR SELLER IF INSTRUMENT IS FX
    IF instrument_param.fx_instrument IS TRUE THEN
        PERFORM process_transfer(
            'INSTRUMENT_SELL'::transfer_type,
            seller_app_entity_instance.pub_id,
            amount_param,
            instrument_param.base_currency,
            'MASTER',
            trade_instance.pub_id,
            trade_instance.pub_id,
            NULL
        );

        PERFORM process_transfer(
            'INSTRUMENT_BUY'::transfer_type,
            'MASTER',
            amount_param * price_param,
            instrument_param.quote_currency,
            seller_app_entity_instance.pub_id,
            trade_instance.pub_id,
            trade_instance.pub_id,
            (CASE seller_trade_order_param = taker_trade_order_param
                WHEN TRUE THEN 'TAKER_FEE'
                WHEN FALSE THEN 'MAKER_FEE'
            END)
        );
    ELSE
        -- transfer instruments directly between two accounts
        PERFORM create_instrument_account_transfer(
            (SELECT pub_id FROM instrument_account WHERE app_entity_id = seller_app_entity_instance.id),
            (SELECT pub_id FROM instrument_account WHERE app_entity_id = buyer_app_entity_instance.id),
            instrument_param,
            amount_param
        );

        -- TODO release any funds that are insufficient for buying an single instument
    END IF;



    -- EXECUTE TRANSFERS FOR BUYER
    PERFORM process_transfer(
        'INSTRUMENT_BUY'::transfer_type,
        buyer_app_entity_instance.pub_id,
        amount_param * price_param,
        instrument_param.quote_currency,
        'MASTER',
        trade_instance.pub_id,
        trade_instance.pub_id,
        NULL
    );

    PERFORM process_transfer(
        'INSTRUMENT_BUY'::transfer_type,
        'MASTER',
        amount_param,
        instrument_param.base_currency,
        buyer_app_entity_instance.pub_id,
        trade_instance.pub_id,
        trade_instance.pub_id,
        (CASE buyer_trade_order_param = taker_trade_order_param
             WHEN TRUE THEN 'TAKER_FEE'
             WHEN FALSE THEN 'MAKER_FEE'
        END)
    );

    -- update open amounts
    UPDATE trade_order
    SET open_amount = open_amount - amount_param,
        status =
            CASE open_amount - amount_param = 0
                WHEN TRUE THEN 'FILLED'::trade_order_status
                WHEN FALSE THEN 'PARTIALLY_FILLED'::trade_order_status
            END
    WHERE id = buyer_trade_order_param.id;

    UPDATE trade_order
    SET open_amount = open_amount - amount_param,
        status =
            CASE open_amount - amount_param = 0
                WHEN TRUE THEN 'FILLED'::trade_order_status
                WHEN FALSE THEN 'PARTIALLY_FILLED'::trade_order_status
            END
    WHERE id = seller_trade_order_param.id;

    IF buyer_trade_order_param = taker_trade_order_param
    AND seller_trade_order_param.order_type = 'LIMIT'::order_type THEN
            PERFORM update_price_level(
                instrument_param.id,
                'SELL',
                price_param,
                amount_param,
                FALSE
            );
    ELSE
        IF buyer_trade_order_param.order_type = 'LIMIT'::order_type THEN
            PERFORM update_price_level(
                instrument_param.id,
                'BUY',
                price_param,
                amount_param,
                FALSE
            );
        END IF;
    END IF;
END;
$$;




-- ── engine/pkg/services/matching/create_book_order.sql ─────────────────────────────────────────────


-- Add the order to the database while increasing the respective price level of
-- This function is meant to be used internally during trade order processing
CREATE OR REPLACE FUNCTION
    create_book_order(
        trade_order_param trade_order
    )
    RETURNS TEXT
    LANGUAGE 'plpgsql' VOLATILE
AS $$
BEGIN
    -- create book_order
    INSERT INTO book_order (trade_order_id)
    VALUES (trade_order_param.id);

    -- update price levels
    PERFORM update_price_level(
        trade_order_param.instrument_id,
        trade_order_param.side,
        trade_order_param.price,
        trade_order_param.open_amount,
        TRUE
    );
    
    RETURN trade_order_param.pub_id;
END;
$$;




-- ── engine/pkg/services/trade_order/cancel_trade_order.sql ─────────────────────────────────────────────

CREATE OR REPLACE FUNCTION
    cancel_trade_order(
        trade_order_id_param text
    )
    RETURNS void
    LANGUAGE 'plpgsql'
AS $$
DECLARE
    instrument_instance instrument%ROWTYPE;
    trade_order_instance trade_order%ROWTYPE;
    order_currency_var text;
    update_amount_var NUMERIC;
BEGIN

    SELECT * FROM trade_order
    WHERE pub_id = trade_order_id_param
    -- allow cancellation only of active orders
    AND status IN ('OPEN'::trade_order_status, 'PARTIALLY_FILLED'::trade_order_status)
    INTO trade_order_instance;

    IF NOT FOUND THEN
        RAISE EXCEPTION 'trade_order_instance_not_found';
    END IF;

    SELECT * FROM instrument
    WHERE id = trade_order_instance.instrument_id
    INTO instrument_instance;

    IF NOT FOUND THEN
        RAISE EXCEPTION 'book_order_instance_not_found';
    END IF;

    -- update price level if order is limit
    IF trade_order_instance.order_type = 'LIMIT'::order_type THEN

        PERFORM update_price_level(
            trade_order_instance.instrument_id,
            trade_order_instance.side,
            trade_order_instance.price,
            trade_order_instance.open_amount,
            FALSE
        );
    END IF;

    -- update trade order status
    IF trade_order_instance.amount != trade_order_instance.open_amount THEN
        UPDATE trade_order
        SET status = 'PARTIALLY_CANCELLED'
        WHERE id = trade_order_instance.id;
    ELSE
        UPDATE trade_order
        SET status = 'CANCELLED'
        WHERE id = trade_order_instance.id;
    END IF;

    -- release funds
    IF trade_order_instance.side = 'SELL'::order_side THEN
        order_currency_var = instrument_instance.base_currency;
        update_amount_var = trade_order_instance.open_amount;
    ELSE
        order_currency_var = instrument_instance.quote_currency;
        update_amount_var = trade_order_instance.open_amount * trade_order_instance.price;
    END IF;

    UPDATE currency_account
    SET amount_reserved = amount_reserved - update_amount_var
    WHERE currency_name = order_currency_var
    AND app_entity_id = (
        SELECT app_entity_id FROM instrument_account ta
        WHERE ta.id = trade_order_instance.instrument_account_id
    );

    -- delete book order
    DELETE FROM book_order WHERE trade_order_id = trade_order_instance.id;
END;
$$;




-- ── engine/pkg/services/matching/activate_crossing_stop_orders.sql ─────────────────────────────────────────────



-- activates all crossing stop limit orders and return true if any have been activated
CREATE OR REPLACE FUNCTION
    activate_crossing_stop_orders(
        instrument_id_param BIGINT,
        order_side_param order_side,
        price_param NUMERIC
    )
    RETURNS BOOLEAN
    LANGUAGE 'plpgsql'
AS $$
DECLARE
    activated_var BOOLEAN := FALSE;
    matching_stop_loss_order_instance trade_order%ROWTYPE;
    matching_stop_limit_order_instance trade_order%ROWTYPE;
BEGIN
    <<stop_loss_loop>>
        FOR matching_stop_loss_order_instance
            IN SELECT * FROM trade_order t
            INNER JOIN stop_order s
                ON s.trade_order_id = t.id
            WHERE t.instrument_id = instrument_id_param
            AND t.price >= price_param
            AND t.side = order_side_param
            AND t.order_type = 'STOPLOSS'::order_type

            LOOP
                DELETE FROM stop_order
                WHERE trade_order_id = matching_stop_loss_order_instance.id;
                -- update order type by turning it into a market order
                UPDATE trade_order
                SET order_type = 'MARKET'::order_type,
                    price = 0
                WHERE id = matching_stop_loss_order_instance.id
                RETURNING * INTO matching_stop_loss_order_instance;
                PERFORM create_book_order(matching_stop_loss_order_instance);
                activated_var := TRUE;
            END LOOP;

    <<stop_limit_loop>>
        FOR matching_stop_limit_order_instance
            IN SELECT * FROM trade_order t
            INNER JOIN stop_order s
                ON s.trade_order_id = t.id
            WHERE t.instrument_id = instrument_id_param
            AND t.price >= price_param
            AND t.side = order_side_param
            AND t.order_type = 'STOPLIMIT'::order_type

            LOOP
                DELETE FROM stop_order
                WHERE trade_order_id = matching_stop_limit_order_instance.id;
                -- update order type
                UPDATE trade_order
                SET order_type = 'LIMIT'::order_type
                WHERE id = matching_stop_limit_order_instance.id
                RETURNING * INTO matching_stop_limit_order_instance;
                PERFORM create_book_order(matching_stop_limit_order_instance);

                activated_var := TRUE;
            END LOOP;

    RETURN activated_var;
END;
$$;




-- ── engine/pkg/services/matching/process_crossing_stop_orders.sql ─────────────────────────────────────────────



-- activates all crossing stop limit orders and return true if any have been activated
CREATE OR REPLACE FUNCTION
    process_crossing_stop_orders(
        instrument_id_param BIGINT,
        order_side_param order_side,
        price_param NUMERIC
    )
    RETURNS void
    LANGUAGE 'plpgsql'
AS $$
DECLARE
    matching_stop_loss_order_instance trade_order%ROWTYPE;
    matching_stop_limit_order_instance trade_order%ROWTYPE;
BEGIN

    <<stop_loss_loop>>
    FOR matching_stop_loss_order_instance
        IN SELECT * FROM trade_order t
        INNER JOIN stop_order s
            ON s.trade_order_id = t.id
        WHERE t.instrument_id = instrument_id_param
        AND s.price >= price_param
        AND t.side = order_side_param
        AND t.order_type = 'STOPLOSS'::order_type

        LOOP
            DELETE FROM stop_order
            WHERE trade_order_id = matching_stop_loss_order_instance.id;
            -- update order type
            UPDATE trade_order
            SET order_type = 'MARKET'::order_type,
                price = 0.00
            WHERE id = matching_stop_loss_order_instance.id;
            PERFORM process_trade_order(
                'VOID',
                (SELECT name FROM instrument WHERE id = instrument_id_param),
                'MARKET',
                order_side_param,
                0,
                matching_stop_loss_order_instance.amount,
                matching_stop_loss_order_instance.time_in_force::text,
                matching_stop_loss_order_instance.id
            );
        END LOOP;

    <<stop_limit_loop>>
    FOR matching_stop_limit_order_instance
        IN SELECT * FROM trade_order t
        INNER JOIN stop_order s
            ON s.trade_order_id = t.id
        WHERE t.instrument_id = instrument_id_param
        AND s.price >= price_param
        AND t.side = order_side_param
        AND t.order_type = 'STOPLIMIT'::order_type

        LOOP
            DELETE FROM stop_order
            WHERE trade_order_id = matching_stop_limit_order_instance.id;
            -- update order type
            UPDATE trade_order
            SET order_type = 'LIMIT'::order_type
            WHERE id = matching_stop_limit_order_instance.id;
            PERFORM process_trade_order(
                'VOID',
                (SELECT name FROM instrument WHERE id = instrument_id_param),
                'LIMIT',
                order_side_param,
                matching_stop_limit_order_instance.price,
                matching_stop_limit_order_instance.amount,
                matching_stop_limit_order_instance.time_in_force::text,
                matching_stop_limit_order_instance.id
            );
        END LOOP;

    RETURN;
END;
$$;



-- ── engine/pkg/services/order_book/get_trade_price.sql ─────────────────────────────────────────────


CREATE OR REPLACE FUNCTION
    get_trade_price(
        taker_side_param order_side,
        taker_order_type_param order_type,
        taker_price_param DECIMAL,
        maker_side_param order_side,
        maker_order_type_param order_type,
        maker_price_param DECIMAL,
        instrument_instance_id_param BIGINT
    )
    -- the trade amount for the order
    RETURNS NUMERIC
    LANGUAGE 'plpgsql'
AS $$
DECLARE
    best_limit_price_var NUMERIC;  -- best limit price available. -1 if not available
    reference_price_var NUMERIC;   -- last trade price, -1 if not available
BEGIN

    -- get best limit price from outstanding limit orders
    SELECT get_best_limit_price(
                   instrument_instance_id_param,
                   maker_side_param
               )
    INTO best_limit_price_var;

    -- get last trade price for reference
    SELECT price FROM trade
    WHERE instrument_id = instrument_instance_id_param
    ORDER BY created_at DESC
    LIMIT 1
    INTO reference_price_var;

    -- handle matching by market orders
    IF taker_order_type_param = 'MARKET'::order_type THEN

        -- incoming market matches on outstanding market in absence of best_limit_price or last trade price
        IF maker_order_type_param = 'MARKET'::order_type
            AND reference_price_var IS NULL
            AND best_limit_price_var = -1 THEN
            RETURN 0;
        END IF;

        -- incoming market matches on outstanding market in absence of best_limit_price but with last trade price
        IF maker_order_type_param = 'MARKET'::order_type
            AND reference_price_var > 0
            AND best_limit_price_var = -1 THEN
            RETURN reference_price_var;
        END IF;

        -- incoming market matches on outstanding market with of best_limit_price available
        IF maker_order_type_param = 'MARKET'::order_type
            AND best_limit_price_var > 0 THEN
            RETURN best_limit_price_var;
        END IF;

        -- incoming market matches an outstanding limit
        IF maker_order_type_param = 'LIMIT'::order_type THEN
            RETURN best_limit_price_var;
        END IF;
    END IF;


    IF taker_order_type_param = 'LIMIT'::order_type THEN
        -- handle matching against limit orders
        IF maker_order_type_param = 'LIMIT'::order_type THEN
            -- limit orders cannot be executed at prices below their limit price
            -- so we always return the match on the limit price in the order book
            -- regardless of takers order type or side
            RETURN maker_price_param;

        END IF;

        IF maker_order_type_param = 'MARKET'::order_type
            AND best_limit_price_var > 0 THEN

            -- for buy orders
            IF taker_side_param = 'BUY'::order_side THEN
                -- if limit matches on market and limit price is less than book order price
                -- then match at incoming orders limit price
                IF taker_price_param < best_limit_price_var THEN
                    RETURN taker_price_param;
                END IF;

                -- if limit matches on market and limit price is more than reference price
                -- then match at reference price
                IF reference_price_var < best_limit_price_var THEN
                    RETURN reference_price_var;
                END IF;
            END IF;

            -- for sell orders
            IF taker_side_param = 'SELL'::order_side THEN

                -- if limit matches on market and limit price is less than reference price
                -- then match at reference price
                IF reference_price_var > best_limit_price_var THEN
                    RETURN reference_price_var;
                END IF;

                -- if limit matches on market and limit price is more than book order price
                -- then match at incoming orders limit price
                IF taker_price_param > best_limit_price_var THEN
                    RETURN taker_price_param;
                END IF;

            END IF;

            RETURN best_limit_price_var;
        END IF;

        -- matching on outstanding market in absence of outstanding limit orders
        -- then match at last traded price
        IF maker_order_type_param = 'MARKET'::order_type
            AND best_limit_price_var = -1
            AND reference_price_var IS NOT NULL THEN
            RETURN reference_price_var;
        END IF;

        -- matching on outstanding market in absence of outstanding limit orders or last trade price
        -- then on orders limit price
        IF maker_order_type_param = 'MARKET'::order_type THEN
            RETURN taker_price_param;
        END IF;

    END IF;

    RAISE EXCEPTION 'no condition found get_trade_price(%,%,%,%,%,%,%)',
        taker_side_param,
        taker_order_type_param,
        taker_price_param,
        maker_side_param,
        maker_order_type_param,
        maker_price_param,
        instrument_instance_id_param;
END;
$$;



-- ── engine/pkg/services/trade_order/process_trade_order.sql ─────────────────────────────────────────────


CREATE OR REPLACE FUNCTION
    process_trade_order(
        instrument_account_id_param text,
        instrument_name_param text,
        order_type_param text,
        side_param order_side,
        price_param NUMERIC,
        amount_param NUMERIC,
        time_in_force_param text,
        trade_order_id_param BIGINT
    )
    RETURNS TEXT -- taker_trade_order.pub_id
    LANGUAGE 'plpgsql'
AS $$
DECLARE
instrument_account_instance instrument_account%ROWTYPE;
    currency_account_instance currency_account%ROWTYPE;
    taker_trade_order_instance trade_order%ROWTYPE; -- saved
    maker_book_order_instance trade_order%ROWTYPE;
    book_order_instance book_order%ROWTYPE;
    instrument_instance instrument%ROWTYPE;

    base_currency_precision INTEGER;
    quote_currency_precision INTEGER;

    opposite_side_var order_side;
    book_order_volume_var NUMERIC;
    total_available_volume_var NUMERIC;
    trade_amount_var NUMERIC;
    order_currency_var text;
    trade_price_var NUMERIC;

    trigger_loop_restart BOOLEAN := FALSE;

    original_amount NUMERIC;
    remaining_amount NUMERIC;

    reserve_amount NUMERIC;
    release_amount NUMERIC;
BEGIN
    -- basic validation
    IF instrument_name_param IS NULL OR length(instrument_name_param) = 0 THEN
        RAISE EXCEPTION 'invalid_instrument';
END IF;

    IF amount_param IS NULL OR amount_param <= 0 THEN
        RAISE EXCEPTION 'invalid_amount';
END IF;

    IF order_type_param IN ('LIMIT','STOPLIMIT') AND (price_param IS NULL OR price_param <= 0) THEN
        RAISE EXCEPTION 'invalid_price';
END IF;

    original_amount := amount_param;
    remaining_amount := amount_param;

    -- load trading account (external mode)
    IF instrument_account_id_param != 'VOID' THEN
SELECT *
FROM instrument_account
WHERE pub_id = instrument_account_id_param
    INTO instrument_account_instance;

IF NOT FOUND THEN
            RAISE EXCEPTION 'instrument_account_instance_not_found';
END IF;
END IF;

    -- load instrument
SELECT *
FROM instrument
WHERE name = instrument_name_param
    INTO instrument_instance;

IF NOT FOUND THEN
        RAISE EXCEPTION 'instrument_instance_not_found';
END IF;

    -- side derived vars (fix := assignment)
    IF side_param = 'SELL' THEN
        opposite_side_var := 'BUY'::order_side;
        order_currency_var := instrument_instance.base_currency;
ELSE
        opposite_side_var := 'SELL'::order_side;
        order_currency_var := instrument_instance.quote_currency;
END IF;

    -- deterministic precision lookups
SELECT c.precision
INTO base_currency_precision
FROM currency c
WHERE c.name = instrument_instance.base_currency;

IF NOT FOUND THEN
        RAISE EXCEPTION 'base_currency_precision_not_found';
END IF;

SELECT c.precision
INTO quote_currency_precision
FROM currency c
WHERE c.name = instrument_instance.quote_currency;

IF NOT FOUND THEN
        RAISE EXCEPTION 'quote_currency_precision_not_found';
END IF;

    IF instrument_account_id_param != 'VOID' THEN
        -- find and lock transfer account row to avoid reservation races
SELECT pa.*
FROM currency_account pa
         INNER JOIN app_entity ae
                    ON pa.app_entity_id = ae.id
WHERE ae.id = instrument_account_instance.app_entity_id
  AND pa.currency_name = order_currency_var
    FOR UPDATE
    INTO currency_account_instance;

IF NOT FOUND THEN
            RAISE EXCEPTION 'currency_account_instance_not_found';
END IF;

        -- normalize inputs to currency precisions
        remaining_amount := round(remaining_amount, base_currency_precision);
        original_amount := remaining_amount;

        IF price_param IS NOT NULL THEN
            price_param := round(price_param, quote_currency_precision);
END IF;

        -- reserve funds (fix precision usage and stable error token)
        IF side_param = 'SELL' OR (side_param = 'BUY' AND order_type_param = 'MARKET') THEN
            reserve_amount := remaining_amount; -- base for SELL, quote for BUY\+MARKET in this model
            IF currency_account_instance.amount - currency_account_instance.amount_reserved < reserve_amount THEN
                RAISE EXCEPTION 'insufficient_funds'
                    USING DETAIL = format(
                        'available=%s required=%s',
                        currency_account_instance.amount - currency_account_instance.amount_reserved,
                        reserve_amount
                    );
END IF;

UPDATE currency_account
SET amount_reserved = round(currency_account.amount_reserved + reserve_amount, base_currency_precision)
WHERE id = currency_account_instance.id;
ELSE
            reserve_amount := banker_round(remaining_amount * price_param, quote_currency_precision);
            IF currency_account_instance.amount - currency_account_instance.amount_reserved < reserve_amount THEN
                RAISE EXCEPTION 'insufficient_funds'
                    USING DETAIL = format(
                        'available=%s required=%s',
                        currency_account_instance.amount - currency_account_instance.amount_reserved,
                        reserve_amount
                    );
END IF;

UPDATE currency_account
SET amount_reserved = round(currency_account.amount_reserved + reserve_amount, quote_currency_precision)
WHERE id = currency_account_instance.id;
END IF;

        -- create trade order
INSERT INTO trade_order (
    instrument_account_id,
    instrument_id,
    order_type,
    side,
    price,
    amount,
    open_amount,
    time_in_force
)
VALUES (
           instrument_account_instance.id,
           instrument_instance.id,
           order_type_param::order_type,
           side_param,
           price_param,
           original_amount,
           original_amount,
           time_in_force_param::order_time_in_force
       )
    RETURNING * INTO taker_trade_order_instance;

ELSE
        -- internal mode
SELECT *
FROM trade_order
WHERE id = trade_order_id_param
    INTO taker_trade_order_instance;

SELECT *
FROM instrument_account
WHERE id = taker_trade_order_instance.instrument_account_id
    INTO instrument_account_instance;

-- in internal mode, remaining\_amount should start from persisted open\_amount
remaining_amount := taker_trade_order_instance.open_amount;
        original_amount := taker_trade_order_instance.amount;
END IF;

    -- stop orders: persist and exit (no matching)
    IF order_type_param = 'STOPLOSS' OR order_type_param = 'STOPLIMIT' THEN
        INSERT INTO stop_order (
            trade_order_id,
            price
        )
        VALUES (
            taker_trade_order_instance.id,
            price_param
        );

RETURN taker_trade_order_instance.pub_id;
END IF;

    -- begin matching
<<matching_loop>>
    LOOP
        total_available_volume_var =
            get_available_market_volume(instrument_instance.id, opposite_side_var)
            + get_available_limit_volume(instrument_instance.id, opposite_side_var, price_param)
            - get_potential_self_trade_volume(instrument_instance.id, opposite_side_var, instrument_account_instance.id, price_param);

        IF taker_trade_order_instance.time_in_force = 'FOK'::order_time_in_force
           AND total_available_volume_var < remaining_amount THEN

UPDATE trade_order
SET status = 'REJECTED'::trade_order_status
WHERE id = taker_trade_order_instance.id;

IF instrument_account_id_param != 'VOID' THEN
                IF side_param = 'SELL' OR (side_param = 'BUY' AND order_type_param = 'MARKET') THEN
                    release_amount := remaining_amount;
UPDATE currency_account
SET amount_reserved = round(currency_account.amount_reserved - release_amount, base_currency_precision)
WHERE id = currency_account_instance.id;
ELSE
                    release_amount := banker_round(remaining_amount * price_param, quote_currency_precision);
UPDATE currency_account
SET amount_reserved = round(currency_account.amount_reserved - release_amount, quote_currency_precision)
WHERE id = currency_account_instance.id;
END IF;
END IF;

RETURN taker_trade_order_instance.pub_id;
END IF;

        -- execute market order trades
<<market_matching_loop>>
        FOR maker_book_order_instance
            IN SELECT t.*
               FROM trade_order t
                        INNER JOIN book_order b
                                   ON b.trade_order_id = t.id
               WHERE t.instrument_id = instrument_instance.id
                 AND t.instrument_account_id != instrument_account_instance.id
                 AND t.side = opposite_side_var
                 AND t.order_type = 'MARKET'::order_type
               ORDER BY t.created_at
                   LOOP
                   trade_price_var := get_trade_price(
                   side_param::order_side,
                   order_type_param::order_type,
                   price_param,
                   opposite_side_var,
                   'MARKET'::order_type,
                   0,
                   instrument_instance.id
                   );

IF trade_price_var IS NULL OR trade_price_var <= 0 OR remaining_amount <= 0 THEN
                EXIT market_matching_loop;
END IF;

            IF side_param = 'SELL' THEN
                trade_amount_var :=
                    banker_round(maker_book_order_instance.open_amount / trade_price_var, quote_currency_precision);
                book_order_volume_var :=
                    maker_book_order_instance.open_amount
                    - banker_round(trade_amount_var * trade_price_var, quote_currency_precision);

                remaining_amount := remaining_amount - trade_amount_var;
ELSE
                IF order_type_param = 'MARKET' THEN
                    IF maker_book_order_instance.open_amount < banker_round(remaining_amount / trade_price_var, quote_currency_precision) THEN
                        trade_amount_var := maker_book_order_instance.open_amount;
ELSE
                        trade_amount_var := banker_round(remaining_amount / trade_price_var, quote_currency_precision);
END IF;

                    remaining_amount := remaining_amount
                        - banker_round(trade_amount_var * trade_price_var, quote_currency_precision);
END IF;

                IF order_type_param = 'LIMIT' THEN
                    IF maker_book_order_instance.open_amount < remaining_amount THEN
                        trade_amount_var := maker_book_order_instance.open_amount;
ELSE
                        trade_amount_var := remaining_amount;
END IF;

                    remaining_amount := remaining_amount - trade_amount_var;
END IF;

                book_order_volume_var := maker_book_order_instance.open_amount - trade_amount_var;
END IF;

            -- dust guard: if rounding drove the fill to zero, stop (no zero-amount
            -- transfer, which would violate transfer_amount_check). Leftover is
            -- released/handled by the post-loop TIF logic.
            IF trade_amount_var IS NULL OR trade_amount_var <= 0 THEN
                EXIT market_matching_loop;
END IF;

            IF book_order_volume_var = 0 THEN
DELETE FROM book_order
WHERE trade_order_id = maker_book_order_instance.id;
END IF;

            IF side_param = 'SELL' THEN
                PERFORM create_trade(
                    instrument_instance,
                    trade_price_var,
                    trade_amount_var,
                    taker_trade_order_instance,
                    maker_book_order_instance,
                    taker_trade_order_instance
                );
ELSE
                PERFORM create_trade(
                    instrument_instance,
                    trade_price_var,
                    trade_amount_var,
                    maker_book_order_instance,
                    taker_trade_order_instance,
                    taker_trade_order_instance
                );
END IF;

            trigger_loop_restart := activate_crossing_stop_orders(
                instrument_instance.id,
                opposite_side_var::order_side,
                trade_price_var
            );

            IF trigger_loop_restart IS TRUE OR remaining_amount = 0 THEN
                EXIT market_matching_loop;
END IF;
END LOOP;

        -- process limit orders
        IF remaining_amount > 0 THEN
            <<limit_matching_loop>>
            FOR book_order_instance
                IN SELECT *
                   FROM get_crossing_limit_orders(
                                instrument_instance.id,
                                opposite_side_var,
                                price_param,
                                instrument_account_instance.id
                        )
                            LOOP
SELECT *
FROM trade_order
WHERE id = book_order_instance.trade_order_id
    INTO maker_book_order_instance;

trade_price_var := get_trade_price(
                    side_param,
                    order_type_param::order_type,
                    price_param,
                    opposite_side_var,
                    'LIMIT'::order_type,
                    maker_book_order_instance.price,
                    instrument_instance.id
                );

                IF trade_price_var IS NULL OR trade_price_var <= 0 THEN
                    EXIT limit_matching_loop;
END IF;

                IF side_param = 'BUY' AND order_type_param = 'MARKET' THEN
                    trade_amount_var := banker_round(remaining_amount / maker_book_order_instance.price, quote_currency_precision);

                    IF maker_book_order_instance.open_amount < trade_amount_var THEN
                        trade_amount_var := maker_book_order_instance.open_amount;
                        book_order_volume_var := 0;
ELSE
                        book_order_volume_var := maker_book_order_instance.open_amount - trade_amount_var;
END IF;

                    remaining_amount := remaining_amount
                        - banker_round(trade_amount_var * maker_book_order_instance.price, quote_currency_precision);
ELSE
                    IF maker_book_order_instance.open_amount < remaining_amount THEN
                        trade_amount_var := maker_book_order_instance.open_amount;
ELSE
                        trade_amount_var := remaining_amount;
END IF;

                    book_order_volume_var := maker_book_order_instance.open_amount - trade_amount_var;
                    remaining_amount := remaining_amount - trade_amount_var;
END IF;

                -- dust guard: stop before emitting a zero-amount trade/transfer.
                IF trade_amount_var IS NULL OR trade_amount_var <= 0 THEN
                    EXIT limit_matching_loop;
END IF;

                IF book_order_volume_var = 0 THEN
DELETE FROM book_order
WHERE id = book_order_instance.id;
END IF;

                IF side_param = 'SELL' THEN
                    PERFORM create_trade(
                        instrument_instance,
                        trade_price_var,
                        trade_amount_var,
                        taker_trade_order_instance,
                        maker_book_order_instance,
                        taker_trade_order_instance
                    );
ELSE
                    PERFORM create_trade(
                        instrument_instance,
                        trade_price_var,
                        trade_amount_var,
                        maker_book_order_instance,
                        taker_trade_order_instance,
                        taker_trade_order_instance
                    );
END IF;

                trigger_loop_restart := activate_crossing_stop_orders(
                    instrument_instance.id,
                    opposite_side_var::order_side,
                    trade_price_var
                );

                IF trigger_loop_restart IS TRUE OR remaining_amount = 0 THEN
                    EXIT limit_matching_loop;
END IF;
END LOOP;
END IF;

        IF trigger_loop_restart IS TRUE THEN
            trigger_loop_restart := FALSE;
ELSE
            EXIT matching_loop;
END IF;
END LOOP;

    -- persist leftover or reject per TIF
    IF remaining_amount > 0 THEN
        IF taker_trade_order_instance.time_in_force = 'IOC'::order_time_in_force THEN
            IF taker_trade_order_instance.open_amount != remaining_amount THEN
UPDATE trade_order
SET status = 'PARTIALLY_REJECTED'::trade_order_status
WHERE id = taker_trade_order_instance.id
    RETURNING * INTO taker_trade_order_instance;
ELSE
UPDATE trade_order
SET status = 'REJECTED'::trade_order_status
WHERE id = taker_trade_order_instance.id
    RETURNING * INTO taker_trade_order_instance;
END IF;

            IF instrument_account_id_param != 'VOID' THEN
                IF side_param = 'SELL' OR (side_param = 'BUY' AND order_type_param = 'MARKET') THEN
UPDATE currency_account
SET amount_reserved = round(currency_account.amount_reserved - remaining_amount, base_currency_precision)
WHERE id = currency_account_instance.id;
ELSE
UPDATE currency_account
SET amount_reserved =
        round(currency_account.amount_reserved - banker_round(remaining_amount * price_param, quote_currency_precision), quote_currency_precision)
WHERE id = currency_account_instance.id;
END IF;
END IF;
ELSE
SELECT *
FROM trade_order
WHERE id = taker_trade_order_instance.id
    INTO taker_trade_order_instance;

PERFORM create_book_order(taker_trade_order_instance);
END IF;
END IF;

    PERFORM process_crossing_stop_orders(instrument_instance.id, side_param::order_side, trade_price_var);

RETURN taker_trade_order_instance.pub_id;
END;
$$;



-- ── engine/pkg/services/order_book/update_price_level.sql ─────────────────────────────────────────────



-- Increases the respective price level
CREATE OR REPLACE FUNCTION
    update_price_level(
        instrument_id_param BIGINT,
        side_param order_side,
        price_param DECIMAL,
        amount_param DECIMAL,
        increasing_param BOOLEAN
    )
    
    -- instrument.pub_id
    RETURNS void

LANGUAGE 'plpgsql'
AS $$
DECLARE
    price_level_instance price_level%ROWTYPE;
BEGIN

    -- update price levels
    SELECT * FROM price_level
    WHERE instrument_id = instrument_id_param
      AND side = side_param
      AND price = price_param
    INTO price_level_instance;

    -- create new price level if not found
    -- for decreasing price level it will always be found
    IF NOT FOUND AND increasing_param = TRUE THEN
        INSERT INTO price_level(
            instrument_id,
            side,
            price,
            volume
        )
        VALUES (
            instrument_id_param,
            side_param,
            price_param,
            amount_param
        );
    ELSE
        IF increasing_param IS TRUE THEN
            UPDATE price_level AS pl
            SET volume = price_level_instance.volume + amount_param
            WHERE pl.price = price_param
            AND pl.side = side_param 
            AND instrument_id = instrument_id_param;
        ELSE
            IF price_level_instance.volume - amount_param < 0 THEN
                RAISE EXCEPTION 'volume_computed_invalid';
            END IF;

            IF price_level_instance.volume - amount_param = 0 THEN
                DELETE FROM price_level 
                WHERE id = price_level_instance.id;
            ELSE
                UPDATE price_level AS pl
                SET volume = price_level_instance.volume - amount_param
                WHERE pl.price = price_param
                AND pl.side = side_param 
                AND instrument_id = instrument_id_param;
            END IF;
        END IF;
    END IF;

END;
$$;



-- ── engine/pkg/services/order_book/get_potential_self_trade_volume.sql ─────────────────────────────────────────────

CREATE OR REPLACE FUNCTION
    get_potential_self_trade_volume(
        instrument_id_param BIGINT, 
        side_param order_side, 
        instrument_account_id_param BIGINT, 
        price_param NUMERIC
    )
    RETURNS NUMERIC
    LANGUAGE 'plpgsql'
AS $$
DECLARE
    acc NUMERIC := 0;
BEGIN
    IF side_param = 'SELL' THEN
        SELECT SUM(open_amount)
        FROM trade_order t
        INNER JOIN book_order b
            ON b.trade_order_id = t.id
        WHERE t.side = side_param
        AND t.instrument_account_id = instrument_account_id_param
        AND t.instrument_id = instrument_id_param
        AND t.price <=  price_param 
        INTO acc;
    ELSE
        SELECT SUM(open_amount)
        FROM trade_order t
        INNER JOIN book_order b
            ON b.trade_order_id = t.id
        WHERE t.side = side_param
        AND t.instrument_account_id = instrument_account_id_param
        AND t.instrument_id = instrument_id_param
        AND (t.price >=  price_param OR t.price = 0.00)
        INTO acc;        
    END IF;

    IF acc IS NULL THEN
        RETURN 0.00;
    END IF;

    RETURN acc;
END;
$$;



-- ── engine/pkg/services/transfer/create_instrument_account_transfer.sql ─────────────────────────────────────────────

CREATE OR REPLACE FUNCTION
  create_instrument_account_transfer(
      from_instrument_account_id_param text,
      to_instrument_account_id_param text,
      instrument_param instrument,
      amount_param integer
  )
  RETURNS TEXT -- instrument_account_transfer.pub_id
LANGUAGE 'plpgsql'
AS $$
DECLARE
  from_instrument_account_instance instrument_account%ROWTYPE;
  to_instrument_account_instance instrument_account%ROWTYPE;
  from_tai instrument_account_holding%ROWTYPE;
  to_tai instrument_account_holding%ROWTYPE;
  transfer_instance instrument_account_transfer%ROWTYPE;
BEGIN
  -- Validate: no self-transfer
  IF from_instrument_account_id_param = to_instrument_account_id_param THEN
    RAISE EXCEPTION 'Self-transfer not allowed --> (%, %)',
        from_instrument_account_id_param,
        to_instrument_account_id_param;
  END IF;
  -- Look up sender instrument account
  SELECT * FROM instrument_account
  WHERE pub_id = from_instrument_account_id_param
  INTO from_instrument_account_instance;
  IF NOT FOUND THEN
      RAISE EXCEPTION 'from_instrument_account_instance_not_found';
  END IF;
  -- Look up receiver instrument account
  SELECT * FROM instrument_account
  WHERE pub_id = to_instrument_account_id_param
  INTO to_instrument_account_instance;
  IF NOT FOUND THEN
      RAISE EXCEPTION 'to_instrument_account_instance_not_found';
  END IF;
  -- Look up sender instrument holding (must exist and have sufficient balance)
  SELECT * FROM instrument_account_holding
  WHERE instrument_account = from_instrument_account_instance.id
    AND instrument_id = instrument_param.id
  INTO from_tai;
  IF NOT FOUND THEN
      RAISE EXCEPTION 'from_instrument_account_holding_not_found';
  END IF;
  IF from_tai.amount < amount_param THEN
      RAISE EXCEPTION 'insufficient_instrument_balance: available %, required %',
          from_tai.amount, amount_param;
  END IF;
  -- Look up or create receiver instrument holding
  SELECT * FROM instrument_account_holding
  WHERE instrument_account = to_instrument_account_instance.id
    AND instrument_id = instrument_param.id
  INTO to_tai;
  IF NOT FOUND THEN
      INSERT INTO instrument_account_holding (instrument_account, instrument_id, amount, amount_reserved)
      VALUES (to_instrument_account_instance.id, instrument_param.id, 0, 0)
      RETURNING * INTO to_tai;
  END IF;
  -- 1. Create the journal entry (transfer header)
  INSERT INTO instrument_account_transfer (
      instrument_id,
      amount,
      details,
      external_reference_number
  ) VALUES (
      instrument_param.id,
      amount_param,
      'Transfer of ' || instrument_param.name,
      NULL
  ) RETURNING * INTO transfer_instance;
  -- 2. Create DEBIT ledger entry (sender side: decrease)
  INSERT INTO instrument_account_ledger_entry (
      transfer_id,
      instrument_account_holding_id,
      entry_type,
      amount,
      resulting_balance
  ) VALUES (
      transfer_instance.id,
      from_tai.id,
      'DEBIT',
      amount_param,
      from_tai.amount - amount_param
  );
  -- 3. Create CREDIT ledger entry (receiver side: increase)
  INSERT INTO instrument_account_ledger_entry (
      transfer_id,
      instrument_account_holding_id,
      entry_type,
      amount,
      resulting_balance
  ) VALUES (
      transfer_instance.id,
      to_tai.id,
      'CREDIT',
      amount_param,
      to_tai.amount + amount_param
  );
  -- 4. Update sender balance (debit reduces the balance)
  UPDATE instrument_account_holding
  SET amount = from_tai.amount - amount_param,
      amount_reserved = (
        CASE WHEN from_tai.amount_reserved >= amount_param
        THEN from_tai.amount_reserved - amount_param
        ELSE 0 END
      ),
      updated_at = current_timestamp
  WHERE id = from_tai.id;
  -- 5. Update receiver balance (credit increases the balance)
  UPDATE instrument_account_holding
  SET amount = to_tai.amount + amount_param,
      updated_at = current_timestamp
  WHERE id = to_tai.id;
  RETURN transfer_instance.pub_id;
END;
$$;


-- ── engine/pkg/services/order_book/get_available_market_volume.sql ─────────────────────────────────────────────



-- Returns available market order volume in base currency for sell 
-- and quote currency for buy
CREATE OR REPLACE FUNCTION get_available_market_volume(
    instrument_id_param BIGINT,
    side_param order_side
)
    RETURNS NUMERIC
    LANGUAGE 'plpgsql'

AS $$
DECLARE
    acc NUMERIC;
BEGIN

    IF side_param = 'SELL' THEN
        SELECT SUM(volume)
        FROM price_level
        WHERE side = side_param
        AND instrument_id = instrument_id_param
        AND price = 0.00
        INTO acc;     
    ELSE
        SELECT SUM(volume)
        FROM price_level
        WHERE side = side_param
        AND instrument_id = instrument_id_param
        AND price = 0.00
        INTO acc;
    END IF;

    IF acc IS NULL THEN
        RETURN 0.00;
    END IF;

    RETURN acc;
END;
$$;



-- ── engine/pkg/services/order_book/get_market_orders.sql ─────────────────────────────────────────────


-- UNUSED
CREATE OR REPLACE FUNCTION
    get_market_orders(
        instrument_id_param BIGINT,
        side_param order_side
    )
    RETURNS setof book_order
    LANGUAGE 'plpgsql'
AS $$
BEGIN
     IF side_param = 'SELL' THEN
        RETURN QUERY SELECT * FROM book_order
        WHERE instrument_id = instrument_id_param
            AND side = side_param
            AND order_type = 'MARKET'::order_type
        -- order first by price then by date created
        ORDER BY created_at;
    ELSE
        RETURN QUERY SELECT * FROM book_order
        WHERE instrument_id = instrument_id_param
            AND side = side_param
            AND order_type = 'MARKET'::order_type
        -- order first by price then by date created
        ORDER BY created_at;
    END IF;
END;
$$;


